version: '3'

networks:
  monitor:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus/prometheus_data:/prometheus
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '9090:9090'
    networks:
      - monitor
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    hostname: alertmanager
    restart: always
    volumes:
      - ./alertmanager:/etc/alertmanager/
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '9093:9093'
    networks:
      - monitor
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
      - '3000:3000'
    networks:
      - monitor
    volumes:
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ino
      - ./grafana/data/:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
      - /data/monitor/grafana/redis-datasource:/var/lib/grafana/plugins
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=v1eZ0n3Gr3f3n3

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    networks:
      - monitor
    restart: unless-stopped
    expose:
      - 9091
    ports:
      - "9091:9091"